blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("test/", views.test)
]

book/urls.py
from django.urls import path, include
from . import views

app_name = "book"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_book, name="saved_book"),
    path("user_books/", views.search_books, name="search_books"),
    path("reload_ok", views.reload_data, name="reload_data"),
    path("save_book/", views.user_book, name="user_book"),
    path("edit_book/", views.edit_book, name="edit_book"),
    path("mypage_edit_book/", views.mypage_edit_book, name="mypage_edit_book"),
    path("mypage_delete_book/", views.mypage_delete_book,
         name="mypage_delete_book"),
]

comfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('contact/', views.contact),

    path('mypage/', include("mypage.urls")),
    path('movie/', include("movie.urls")),
    path('blog/', include("blog.urls")),
    path('idea/', include("idea.urls")),
    path('book/', include("book.urls")),
    path('english/', include("english.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.urls import path, include
from . import views

app_name = "idea"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.idea_home, name="idea_home"),
    path("save_idea/", views.save_idea, name="save_idea"),
    path('user_idea/<int:idea_id>/', views.user_idea, name='user_idea'),
    path("idea_edit/", views.idea_edit, name="idea_edit"),
]

movie/urls.py
from django.urls import path, include
from . import views

app_name = "movie"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_movie, name="saved_movie"),
    path("user_movies/", views.search_movies, name="search_movies"),
    path("save_movie/", views.user_movie, name="user_movie"),
    path("edit_movie/", views.edit_movie, name="edit_movie"),
    path("mypage_edit_movie/", views.mypage_edit_movie, name="mypage_edit_movie"),
    path("mypage_delete_movie/", views.mypage_delete_movie,
         name="mypage_delete_movie"),
    path("like=<int:id>/", views.like, name="like"),
]

mypage/urls.py
from django.urls import path, include
from . import views

app_name = "mypage"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.mypage, name="mypage"),
    path("my_edit/", views.profile_edit, name="profile_edit"),
    path("email_save/", views.profile_email_save, name="profile_email_save"),
    path("password_save/", views.profile_password_save,
         name="profile_password_save"),
    path("my_movie/", views.mypage_tab1, name="mypage_tab1"),
    path("my_book/", views.mypage_tab2, name="mypage_tab2"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/<int:idea_id>/", views.mypage_tab3_user, name="mypage_tab3_user"),
    path("my_english/", views.mypage_tab5, name="mypage_tab5"),
]

mypage/models.py
from django.db import models

# Create your models here.

mypage/forms.py
from django import forms
from django.core.exceptions import ValidationError
from mysite.models import User

# ログイン
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


class ChangePasswordForm(forms.Form):
    """パスワード変更"""
    current_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )
    new_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )
    confirm_new_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )

    def __init__(self, user_id, *args, **kwargs):
        self.user_id = user_id
        super().__init__(*args, **kwargs)

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']
        user = User.objects.get(id=self.user_id)
        if user.username and current_password:
            auth_result = authenticate(
                username=user.username,
                password=current_password,
            )
            if not auth_result:
                raise ValidationError('現在のパスワードが間違っています。')
        return current_password

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        return new_password

    def clean_confirm_new_password(self):
        confirm_new_password = self.cleaned_data['confirm_new_password']
        return confirm_new_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = self.cleaned_data.get('new_password')
        confirm_new_password = self.cleaned_data.get('confirm_new_password')
        if new_password != confirm_new_password:
            self.add_error(
                field='confirm_new_password',
                error=ValidationError('パスワードが一致しません。'))
        return cleaned_data


# 画像アップロード(modelの定義)
class UploadForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('account_image',)

mypage/views.py
from django.shortcuts import render, redirect
from movie.models import UserMovie
from book.models import UserBook
from idea.models import UserIdea, ThreadComment
from english.models import UserEnglish
from mysite.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from mypage.forms import UploadForm


def mypage(request):
    context = {}
    user_id = request.user.id
    db_movie_objs = UserMovie.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_book_objs = UserBook.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_idea_objs = UserIdea.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_english_objs = UserEnglish.objects.filter(
        user_id=user_id).order_by("id").reverse()[:4]

    # 総数取得
    movie_count = UserMovie.objects.all().filter(
        user_id=user_id).count()
    book_count = UserBook.objects.all().filter(
        user_id=user_id).count()
    idea_count = UserIdea.objects.all().filter(
        user_id=user_id).count()
    english_count = UserEnglish.objects.all().filter(
        user_id=user_id).count()

    db_user_objs = User.objects.all().filter(id=user_id)

    context["latest_movie"] = db_movie_objs
    context["latest_book"] = db_book_objs
    context["latest_idea"] = db_idea_objs
    context["latest_english"] = db_english_objs
    context["user_profile"] = db_user_objs

    context["movie_count"] = movie_count
    context["book_count"] = book_count
    context["idea_count"] = idea_count
    context["english_count"] = english_count

    return render(request, "mypage/mypage.html", context)


# プロフィール編集処理
def profile_edit(request):

    # プロフィール情報表示する
    try:
        context = {}
        if request.method == "POST":
            # 画像アップロード
            form = UploadForm(request.POST, request.FILES,)
            context["form"] = form

            profile_id = request.POST["profile_edit"]
            db_user_objs = User.objects.all().filter(id=profile_id)
            context["profile_data"] = db_user_objs

    except:
        print("プロフィールデータが取得出来ませでした")

    return render(request, "mypage/profile_edit.html", context)


def profile_email_save(request):

    # ユーザー情報(email)DB変更処理
    if request.method == "POST":
        profile_id = request.POST["email_edit"]
        account_image = request.POST.get("account_image")
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        user_name = request.POST["user_name"]
        user_email = request.POST["user_email"]
        print(account_image, "aaaaaaa")

        User.objects.filter(id=profile_id).update(
            firstName=first_name, lastName=last_name, username=user_name, email=user_email, account_image=account_image)

    else:
        print("ユーザー情報が取得出来ませでした")

    return redirect("/mypage")


def profile_password_save(request):

    # パスワード変更処理
    if request.method == "POST":
        profile_id = request.POST["password_edit"]

        # inputされたパスワード
        now_password = request.POST["now_password"]

        # DBのハッシュ化されているパスワード取得
        now_db = User.objects.get(id=profile_id)
        now_db_password = now_db.password

        if now_password:
            new_password = request.POST["new_password"]
            new_password_again = request.POST["new_password_again"]

            if new_password == new_password:
                User.objects.filter(id=profile_id).update(
                    password=new_password_again)

            else:
                print("新しいパスワードが同じではありません")
        else:
            print("パスワードが違います")

    else:
        print("パスワード情報が取得出来ませでした")

    return redirect("/mypage")


def mypage_tab1(request):

    user_id = request.user.id
    db_objs = UserMovie.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)
    page = request.GET.get('page', 1)
    obj_count = UserMovie.objects.all().count()
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    context = {'pages': pages, 'count': obj_count}

    return render(request, "mypage/mypage_segment/mypage_tab1.html", context)


def mypage_tab2(request):

    user_id = request.user.id
    db_objs = UserBook.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)

    page = request.GET.get('page', 1)
    obj_count = UserBook.objects.all().count()

    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    context = {'pages': pages, 'count': obj_count}

    return render(request, "mypage/mypage_segment/mypage_tab2.html", context)


def mypage_tab3(request):

    context = {}
    image_array = []

    user_id = request.user.id
    objs = UserIdea.objects.filter(user_id=user_id).order_by("id")[::-1]
    obj_count = UserIdea.objects.all().count()
    if objs:
        context["db_ideas"] = objs
        for obj in objs:
            # account_image取り出し
            user_id = obj.user_id
            objs = User.objects.filter(id=user_id)
            for obj in objs:
                account_image = obj.account_image
                image_array.append(account_image)

        context["account_image"] = image_array
        context["obj_count"] = obj_count
    else:
        print("DBから所得できてない")

    return render(request, "mypage/mypage_segment/mypage_tab3.html", context)


def mypage_tab3_user(request, idea_id):
    context = {}

    "通常表示用"
    context = {}
    image_array = []
    objs = UserIdea.objects.order_by("id")[::-1][:10]
    obj_count = UserIdea.objects.all().count()
    if objs:
        context["db_ideas"] = objs
        for obj in objs:
            # account_image取り出し
            user_id = obj.user_id
            objs = User.objects.filter(id=user_id)
            for obj in objs:
                account_image = obj.account_image
                image_array.append(account_image)

        context["account_images"] = image_array
        context["obj_count"] = obj_count
    else:
        print("DBから所得できてない")

    # コメント投稿後処理
    request.method == "POST"
    if request.POST.get("add_comment_btn"):
        idea_id = request.POST.get("add_comment_btn")
        if idea_id:
            comment_user_id = request.POST["user_id"]
            user_info = User.objects.get(id=comment_user_id)
            account_image = user_info.account_image
            comment_username = request.POST["user_name"]
            got_comment = request.POST["comment_form"]
            ThreadComment.objects.create(
                user_id=comment_user_id, username=comment_username, account_image=account_image, idea_id=idea_id, comment=got_comment)
    else:
        print("コメント投稿後処理ができませんでした")

    # コメント削除ボタン処理
    try:
        edit_id = request.POST["comment_delete_btn"]
        if edit_id:
            ThreadComment.objects.filter(id=edit_id).delete()
        else:
            print("edit_idが受け取れませんでした。")
    except:
        print("削除処理失敗しました")

    # 選択されたIdeaの詳細
    user_idea = UserIdea.objects.get(id=idea_id)
    if user_idea:
        context["idea_id"] = user_idea.id
        context["user_id"] = user_idea.user_id
        context["idea_title"] = user_idea.idea_title
        context["username"] = user_idea.username
        context["idea_detail"] = user_idea.idea_detail
        context["idea_from"] = user_idea.idea_from
        context["idea_tag"] = user_idea.idea_tag
        context["created_at"] = user_idea.created_at
        context["idea_price"] = user_idea.idea_price
        context["idea_target"] = user_idea.idea_target
        context["idea_for"] = user_idea.idea_for
        # tag取り出し
        idea_tag = user_idea.idea_tag
        idea_tag = idea_tag.replace(",", " ").replace(
            "、", " ").replace("　", " ").replace(".", "")
        tag_list = idea_tag.split(" ")
        context["idea_tag"] = tag_list

        # account画像取り出し
        got_id = user_idea.user_id
        objs = User.objects.get(id=got_id)
        context["account_image"] = objs.account_image

        # commentの取得
        # 全て表示
        comment_count = ThreadComment.objects.filter(idea_id=idea_id).count()
        more_btn = request.POST.get("more_btn")
        if more_btn:
            print(more_btn)
            user_comment = ThreadComment.objects.filter(idea_id=idea_id)
            context["comment_count"] = 1
        # 初期表示
        else:
            user_comment = ThreadComment.objects.filter(idea_id=idea_id)[:2]
            context["comment_count"] = comment_count
        context["user_comment"] = user_comment
        context["user_comment_id"] = idea_id

    else:
        print("DBから所得できてない")
    return render(request, 'mypage/mypage_segment/mypage_tab3_user.html', context)


def mypage_tab5(request):

    context = {}

    # 単語の表示
    user_id = request.user.id
    db_objs = UserEnglish.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)

    page = request.GET.get('page', 1)
    obj_count = UserEnglish.objects.all().count()

    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    # checkボタンDB保存
    check_content = request.POST.getlist("check_content")
    saved_id = request.POST.get("check_save_btn")

    if check_content:
        if "1times" in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_1="checked")
        elif "1times" not in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_1="unchecked")

        if "2times" in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_2="checked")

templates/mypage/mypage_segment/mypage_header.html
{% load static %}
<!-- トップバー -->
<nav class="navbar px-3 py-0 my-4 bg-light position-static justify-content-center" id="navbar">
    <!-- 中央画像 -->
    <!-- text-muted mx-auto -->
    <a class="home_button position-absolute" style="color:inherit; text-decoration:none;" href="/">
        <p class="nav-item-underline mb-0 link-secondary">HOME</p>
    </a>
    <a class="mypage_button position-absolute" style="color:inherit; text-decoration:none;" href="{% url 'mypage:mypage' %}">
        <p class="nav-item-underline mb-0 link-secondary">MYPAGE</p>
    </a>
    <a class="nav-item-image" href="/">
        <img src="{{ STATIC_URL }}img/header.jpg" class="text-muted" width="200" height="100" alt="サンプル">
    </a>
    <ul class="navbar-nav d-flex flex-row position-absolute end-0">
        <li class="nav-item-underline ml-3 text-muted">
            <a class="p-2 link-secondary" href="#" style="text-decoration:none;">ABOUT</a>
        </li>
        <li class="nav-item-underline ml-3 text-muted">
            <a class="p-2 link-secondary" href="/contact" style="text-decoration:none;">CONTACT</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item-underline mx-3 text-muted">
            <a class="p-2 link-secondary" href="/logout" style="text-decoration:none;">LOGOUT</a>
        </li>
        {% else %}
        <li class="nav-item-underline mx-3 text-muted">
            <a class="p-2 link-secondary" href="/login" style="text-decoration:none;">LOGIN</a>
            <a>/</a>
            <a class="p-2 link-secondary" href="/signup" style="text-decoration:none;">SIGNUP</a>
        </li>
        {% endif %}
    </ul>
</nav>
<!-- トップバー -->

templates/mypage/mypage_segment/mypage_segment.html
<!-- 各appのHomeを作成してurlを通したらその都度urlを変更する -->
<!-- 小さいheader -->
<div class="main-wrapper" id="mainwrapper">
  <form class="img_container main-box1" action="{% url 'mypage:mypage_tab1' %}" method="POST">
      <a class="box box1" href="{% url 'mypage:mypage_tab1' %}">Movie</a>
  </form> 
  <div class="img_container main-box2">
      <a class="box box2" href="#">Blog</a>
  </div>
  <div class="img_container main-box3">
      <a class="box box3" href="{% url 'mypage:mypage_tab3' %}">Idea</a>
  </div>
  <form class="img_container main-box4" action="{% url 'mypage:mypage_tab2' %}" method="POST">
      <a class="box box4" href="{% url 'mypage:mypage_tab2' %}">Book</a>
  </form>
  <div class="img_container main-box5">
      <a class="box box5" href="{% url 'mypage:mypage_tab5' %}">English</a>
  </div>
</div>
<!-- 小さいheader --> 

templates/mypage/mypage_segment/mypage_tab1.html
{% extends 'mysite/base.html' %}
{% load static %}
{% load boost %}
 
{% block head %} 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/mypage.css' %}">

{% endblock %}

{% block content %}
<main class="h-100">
    <div class="page-wrapper d-flex flex-row h-100 w-100">
      
      <!-- 全ページの右のコンテンツ -->
        <div class="page-content h-100 w-100">

            {% include 'mypage/mypage_segment/mypage_header.html' %}
            {% include 'mypage/mypage_segment/mypage_segment.html' %}

            <!-- 下のコンテンツ -->
            <div class="big-display">

              <div class="page_title w-100 pt-5 pb-3">
                <p class="mypage_title">映画ページ({{count}})</p>
              </div>

              <!-- search_movie_all -->
              <div class="mypage_row px-5">
                <!-- movie_row -->
                {% for movie in pages %}
                <div class="mypage_data_row d-flex flex-row mx-3 mb-4" style="border: 1px solid rgb(0, 0, 0, 0.1);"> 
                  <img src="https://image.tmdb.org/t/p/w92{{movie.poster_path}}" class="movie_mypage_img p-2">
                  <div class="p-2 w-100">
                    <div class="top_row w-100">
                      <div class="scroll_title d-flex w-100">
                        <p class="movie_title mb-1">{{movie.title}}</p>
                      </div>                
                      <div class="d-flex flex-row pt-2">
                        <p class="release_date m-0 pr-4">視聴日:　<strong>{{movie.created_at|date:"Y-m-d"}}</strong></p>
                        <p class="vote_average m-0">評価:　<strong>{{movie.vote_rate}} / 10</strong></p>
                      </div>
                      <p class="vote_average pt-2 mb-2">感想:　<strong>{{movie.summary}}</strong></p>
                      <a href="https://www.themoviedb.org/movie/{{movie.movie_id}}?language=ja" class="detail_btn mt-2 mr-2 mb-0">詳細ページへ</a>

                    </div>
                    <!-- ここに線を入れたい -->
                    <div class="under_row d-flex flex-row mt-2">
                      {% if user.is_authenticated %}
                        <form class="save_button pt-1 pr-2" action="{% url 'movie:mypage_edit_movie' %}" method="POST">
                          {% csrf_token %} 
                          <button type="submit" name="mypage_edit_btn" class="btn btn-sm btn-secondary" value={{movie.id}}>編集</button>
                        </form>
                         
                        <form class="save_button pt-1" action="{% url 'movie:mypage_delete_movie' %}" method="POST">
                          {% csrf_token %} 
                          <button type="submit" name="mypage_delete_btn" class="btn btn-sm btn-danger" value={{movie.id}}>削除</button>
                        </form>
                        {% endif %}
                    </div> 
                  </div> 
                </div>
                {% endfor %}
                <!-- movie_row -->
              </div>
              <div class="pagenations pt-4 pb-3">
                {% if pages.has_other_pages %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if pages.has_previous %}
                            <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.previous_page_number }}"><<</a></li>
                        {% else %}
                            <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#"><<</div></li>
                        {% endif %}
            
                        {% if pages.has_previous %}
                            {% if pages.previous_page_number != 1 %}
                                <li><a class="page-link text-primary d-inline-block" href="?page=1">1</a></li>
                                <li>…</li>
                            {% endif %}
                            <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.previous_page_number }}">{{ pages.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ pages.number }}</div></li>
                        {% if pages.has_next %}
                            <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.next_page_number }}">{{ pages.next_page_number }}</a></li>
                            {% if pages.next_page_number != pages.paginator.num_pages %}
                                <li>…</li>
                                <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.paginator.num_pages }}">{{ pages.paginator.num_pages }}</a></li>
                            {% endif %}
                        {% endif %}
                        {% if pages.has_next %}
                            <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.next_page_number }}">>></a></li>
                        {% else %}
                            <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">>></div></li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
              </div>
              <!-- search_movie_all -->
            </div>
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}

templates/mypage/mypage_segment/mypage_tab3_user.html
{% extends 'mysite/base.html' %}
{% load static %}
{% load boost %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/idea.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/mypage.css' %}">
{% endblock %}

{% block content %}
<main class="h-100">
    <div class="page-wrapper d-flex flex-row h-100 w-100">
      
      <!-- 全ページの右のコンテンツ -->
      <div class="page-content h-100 w-100">

        {% include 'mypage/mypage_segment/mypage_header.html' %}
        {% include 'mypage/mypage_segment/mypage_segment.html' %}

        <div class="big-display w-100 h-100">
            
            <div class="page_title w-100 pt-5 pb-3">
                <p class="mypage_title">アイデアページ({{obj_count}})</p>
            </div>

            <div class="idea_content mt-4 ml-5 d-flex flex-row">
                <!-- user_idea_content -->
                <div class="user_idea_content d-flex flex-column">
                <p class="saved_header mb-1">ユーザーが最近投稿したアイデア</p>
                <!-- saved_idea_row -->
                {% for idea,account_image in db_ideas|zip:account_images %}
                    <div class="saved_idea_row d-flex flex-row px-3 pt-2 pb-1">
                    <div class="right_idea_row d-flex flex-column w-100">
                        <div class="user_idea_title_row">
                        <a href="{% url 'mypage:mypage_tab3_user' idea_id=idea.id %}" class="user_idea_title mr-2 mb-0" id="title_clicked">{{idea.idea_title}}</a>
                        </div>
                        <div class="user_name_row d-flex flex-row">
                        <p class="pr-3 mb-0">いいね</p>
                        <p class="created_at pr-3 m-0">{{idea.created_at|date:"Y-m-d"}}</p>
                        <p class="username mb-0">{{idea.username}}</p>
                        {% if user.id == idea.user_id %}
                            <form class="save_button ml-3 mb-1 mt-0" action="{% url 'idea:idea_edit' %}" method="POST">
                            {% csrf_token %} 
                            <button type="submit" name="db_edit_btn" class="btn btn-sm btn-secondary" value={{idea.id}}>編集</button>
                            <button type="submit" name="db_delete_btn" class="btn btn-sm btn-danger" value={{idea.id}}>削除</button>
                            </form>
                        {% endif %}
                        </div>
                    </div>
                    </div>
                {% endfor %}
                <!-- saved_idea_row -->
                </div>
                <!-- user_idea_content -->
                <div class="thread_content d-flex flex-column mb-5">
                    <p class="saved_header mb-1">{{username}}さんが最近投稿したアイデア</p>
                    <!-- saved_idea_row -->
                    <div class="saved_idea_row d-flex flex-row px-3 pt-2 pb-1">
                        <div class="right_idea_row d-flex flex-column w-100">
                            <div class="user_idea_title_row">
                                <p class="user_detail_title mb-0" >{{idea_title}}</p>
                            </div>

                            <div class="idea_row d-flex flex-row mt-3">
                                <p class="detail_row_title">アイデア詳細</p>
                                <p>{{idea_detail}}</p>
                            </div>
                            <div class="idea_row d-flex flex-row mt-3">
                                <p class="detail_row_title">タグ(検索用ワード)</p>
                                {% for tag in idea_tag %}
                                <p class="mr-2">{{tag}}</p>
                                {% endfor %}
                            </div>
                            <div class="idea_row d-flex flex-row mt-3">
                                <p class="detail_row_title">思いついたきっかけ</p>
                                <p>{{idea_from}}</p>
                            </div>
                            <div class="idea_row d-flex flex-row mt-3">
                                <p class="detail_row_title">アイデア用途</p>
                                <p>{{idea_for}}</p>
                            </div>
                            <div class="idea_row d-flex flex-row mt-3">
                                <p class="detail_row_title">アイデアターゲット</p>
                                <p>{{idea_target}}</p>
                            </div>
                            <div class="idea_row_last d-flex flex-row mt-3">
                                <p class="detail_row_title">販売希望価格</p>
                                <p class="price_subtitle">{{idea_price}}円(税込)</p>
                            </div>

                            <div class="detail_user_name_row d-flex flex-row pt-2">
                                <p class="mr-5 mb-0">いいね</p>
                                <p class="created_at mr-5 m-0">{{created_at|date:"Y-m-d"}}</p>
                                <p class="mb-0">by <span class="username">{{username}}</span></p>
                            </div>
                            <div class="comment_form　mt-3 mb-4 w-100">
                            <form method="POST" action="" class="w-100 d-flex flex-row">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{user_id}}">
                                <input type="hidden" name="user_name" value="{{username}}">
                            </form>
                            </div>
                        </div>
                    </div>
                    <!-- saved_idea_row -->
                    {% if user_comment %}
                    <div class="comment_content mt-3">
                    {% for comment in user_comment%}
                    <div class="comment_content_row d-flex flex-row py-2">
                        <img src="{{comment.account_image}}" class="comment_account_image ml-2 mr-3 mb-3">
                        <div class="right_idea_row w-100 mr-2">
                        <div class="user_idea_title_row">
                            <p class="idea_comment mr-2 mb-0">{{comment.comment}}</p>
                        </div>
                        <div class="comment_user_name_row d-flex flex-row1">
                            <p class="mr-4 mb-0">いいね</p>
                            <p class="created_at mr-4 m-0">{{comment.created_at|date:"Y-m-d"}}</p>
                            <p class="mb-0">by <span class="username">{{comment.username}}</span></p>
                            {% if user.id == comment.user_id %}
                            <form class="save_button ml-3　mb-0 mt-0" action="{% url 'idea:user_idea' idea_id=comment.idea_id %}" method="POST">
                            {% csrf_token %} 
                            <button type="submit" name="comment_delete_btn" class="btn btn-sm btn-danger" value={{comment.id}}>削除</button>
                            </form>
                            {% endif %}
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <!-- user_idea_content -->
            </div>
        <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}