blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("test/", views.test)
]

book/urls.py
from django.urls import path, include
from . import views

app_name = "book"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_book, name="saved_book"),
    path("user_books/", views.search_books, name="search_books"),
    path("reload_ok", views.reload_data, name="reload_data"),
    path("save_book/", views.user_book, name="user_book"),
    path("edit_book/", views.edit_book, name="edit_book"),
    path("mypage_edit_book/", views.mypage_edit_book, name="mypage_edit_book"),
    path("mypage_delete_book/", views.mypage_delete_book,
         name="mypage_delete_book"),
]

comfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('contact/', views.contact),

    path('mypage/', include("mypage.urls")),
    path('movie/', include("movie.urls")),
    path('blog/', include("blog.urls")),
    path('idea/', include("idea.urls")),
    path('book/', include("book.urls")),
    path('english/', include("english.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models


class UserBook(models.Model):
    title = models.CharField(max_length=50)
    itemUrl = models.CharField(max_length=100)
    ImageUrl = models.CharField(max_length=50)
    salesDate = models.CharField(max_length=15)
    vote_rate = models.CharField(default="評価なし", max_length=2)
    summary = models.CharField(default="感想・要約が入力されていません", max_length=150)
    auther = models.CharField(max_length=30)
    user_id = models.IntegerField()
    # tagといいねもつけたい
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.id)


class BookAPI(models.Model):
    ImageUrl = models.CharField(max_length=50)
    item_Url = models.CharField(max_length=50)
    book_id = models.IntegerField()

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.id)

book/views.py
import imp
from django.shortcuts import redirect, render
import requests
import json
from book.models import UserBook, BookAPI
import re
import environ

# from datetime import datetime
import datetime

env = environ.Env()
applicationId = env("applicationId")
# 保存後の処理


def saved_book(request):
    context = {}

    # idをsave_btnから引っ張ってくる
    try:
        # POSTされたIDを取得
        request.method == "POST"
        # textareaの情報
        sum_text = request.POST["sum_text"]
        saved_isbn = request.POST["save_btn"]
        vote_rate = request.POST["vote_rate"]

        if sum_text:
            summary = sum_text
        else:
            summary = "感想・要約は記入されていません"

        api = "https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404?format=json&isbn={}&applicationId="+str(applicationId).format(
            saved_isbn)

        # 実際にAPIにリクエストを送信して結果を取得する
        search_books_api = requests.get(api).text
        # 結果はJSON形式なのでデコードする
        search_books = json.loads(search_books_api)
        # 結果を表示
        if search_books:
            # isbnで特定の一つのみ取得しているため[0]で一つだけ取得
            saved_result = search_books['Items'][0]["Item"]

            saved_title = saved_result["title"]
            saved_url = saved_result["itemUrl"]
            saved_largeImageUrl = saved_result["smallImageUrl"]

            salesDate = saved_result["salesDate"]

            salesDate = salesDate.replace("頃", "").replace("日", "")
            salesDate = re.split("年|月", salesDate)
            salesDate = [text if text !=
                         "" else "??" for text in salesDate]

            salesDate = "-".join(salesDate)

            now_logging_user_id = request.user.id
            # ログインしているユーザー名取得
            now_logging_user = request.user.username
            # DBに追加
            UserBook.objects.create(
                title=saved_title, itemUrl=saved_url, ImageUrl=saved_largeImageUrl, salesDate=salesDate, vote_rate=vote_rate, summary=summary, auther=now_logging_user, user_id=now_logging_user_id)
            print("DBに保存されました")
        else:
            print("書籍を取得できませんでした")
    except:
        print("You failed POST")

    # 編集・削除のボタンが押された後の処理
    # summaryとrateを受け取る
    try:
        # POSTされたDB_IDを取得
        request.method == "POST"
        if request.POST["db_edit_btn"]:
            print("変更処理がされました")
            db_id = request.POST["db_edit_btn"]
            sum_text = request.POST["sum_text"]
            vote_rate = request.POST["vote_rate"]
            btn_from = request.POST["btn_from"]

            if sum_text:
                summary = sum_text
            else:
                summary = "感想・要約は記入されていません"
            UserBook.objects.filter(id=db_id).update(
                summary=summary, vote_rate=vote_rate)

            if btn_from == "mypage_tab2":
                return redirect("/mypage/my_book")
        else:
            ("編集ボタンが認証できませんでした")

    except:
        print("変更処理が通っていません")

    try:
        # POSTされたDB_IDを取得
        request.method == "POST"
        if request.POST["db_delete_btn"]:
            print("削除処理がされました")
            db_id = request.POST["db_delete_btn"]
            UserBook.objects.filter(id=db_id).delete()
        else:
            print("削除ボタン情報が認証できませんでした")
    except:
        print("削除処理が通っていません")

    # DBに保存されたデータを取り出す
    # DBから最新ObjectをN個取り出す
    try:
        objs = UserBook.objects.order_by("id")[::-1][:5]
        if objs:
            context["db_books"] = objs
        else:
            print("DB情報が取得出来ませんでした")
    except:
        print("DB読まれてもない")

    # その日の20個を表示
    # [::-1][:30]
    objs1 = BookAPI.objects.filter(
        book_id=1).order_by("id")[:60]
    objs2 = BookAPI.objects.filter(
        book_id=2).order_by("id")[:60]
    objs3 = BookAPI.objects.filter(
        book_id=3).order_by("id")[:60]

    context["got_book1"] = objs1
    context["got_book2"] = objs2
    context["got_book3"] = objs3

    return render(request, "book/books.html", context)


# リロード(1日1回)
def reload_data(request):

    print("リロードされたよ")
    context = {}
    # # DB一日前の削除・更新
    # try:
    request.method == "POST"
    search_query = request.POST["reload_btn"]
    if search_query == "":
        d_today = datetime.date.today()  # 現在日付の取得
        print(d_today)
        before_1_days = d_today - datetime.timedelta(days=1)
        print(before_1_days)
        if BookAPI.objects.filter(created_at__lte=before_1_days).exists():
            print(BookAPI.objects.filter(
                created_at__lte=before_1_days).count(), "1日前までの動画数")
            print(BookAPI.objects.all().count(), "今日までの総動画数")
            BookAPI.objects.filter(
                created_at__lte=before_1_days).delete()
            print(BookAPI.objects.all().count(), "消去後の総動画数")
            print("削除されました")
        else:
            print("1日前のデータがありません")
    else:
        print("機能していない")
    # except:
    #     print("reloadできていません")

    # API取得処理
    ranking_api = "https://app.rakuten.co.jp/services/api/IchibaItem/Ranking/20170628?applicationId=1091122717356551414&genreId={}&page=1"
    ranking_api2 = "https://app.rakuten.co.jp/services/api/IchibaItem/Ranking/20170628?applicationId=1091122717356551414&genreId={}&page=2"

    essay_id = 101266
    business_id = 200446
    paperbook_id = 101937

    # api1
    essay = ranking_api.format(essay_id)
    bussines = ranking_api.format(business_id)
    paperbook = ranking_api.format(paperbook_id)

    search_essay_api = requests.get(essay).text
    search_bussines_api = requests.get(bussines).text
    search_paperbook_api = requests.get(paperbook).text

    # 結果はJSON形式なのでデコードする
    essay_ranking = json.loads(search_essay_api)
    bussines_ranking = json.loads(search_bussines_api)
    paperbook_ranking = json.loads(search_paperbook_api)

    # api=2
    essay2 = ranking_api2.format(essay_id)
    bussines2 = ranking_api2.format(business_id)
    paperbook2 = ranking_api2.format(paperbook_id)

    search_essay_api2 = requests.get(essay2).text
    search_bussines_api2 = requests.get(bussines2).text
    search_paperbook_api2 = requests.get(paperbook2).text

    # 結果はJSON形式なのでデコードする
    essay_ranking2 = json.loads(search_essay_api2)
    bussines_ranking2 = json.loads(search_bussines_api2)
    paperbook_ranking2 = json.loads(search_paperbook_api2)

    # essay_ranking
    if essay_ranking:
        saved_result = essay_ranking['Items']

        for i in saved_result:
            item = i["Item"]
            image = item["mediumImageUrls"][0]
            thumbnail_image = image["imageUrl"]
            item_url = item["itemUrl"]

            BookAPI.objects.create(
                ImageUrl=thumbnail_image, item_Url=item_url, book_id=1)

    else:
        print("essay_rankingが取得できませんでした")

    # if essay_ranking2:
    #     saved_result = essay_ranking2['Items']

    #     for i in saved_result:
    #         item = i["Item"]
    #         image = item["mediumImageUrls"][0]
    #         thumbnail_image = image["imageUrl"]
    #         item_url = item["itemUrl"]

    #         BookAPI.objects.create(
    #             ImageUrl=thumbnail_image, item_Url=item_url, book_id=1)

    # else:
    #     print("essay_ranking2が取得できませんでした")

    # bussines_ranking
    if bussines_ranking:
        saved_result = bussines_ranking['Items']

        for i in saved_result:
            item = i["Item"]
            image = item["mediumImageUrls"][0]
            thumbnail_image = image["imageUrl"]
            item_url = item["itemUrl"]

            BookAPI.objects.create(
                ImageUrl=thumbnail_image, item_Url=item_url, book_id=2)

    else:
        print("bussines_rankingが取得できませんでした")

    # if bussines_ranking2:
    #     saved_result = bussines_ranking2['Items']

    #     for i in saved_result:
    #         item = i["Item"]
    #         image = item["mediumImageUrls"][0]
    #         thumbnail_image = image["imageUrl"]
    #         item_url = item["itemUrl"]

    #         BookAPI.objects.create(
    #             ImageUrl=thumbnail_image, item_Url=item_url, book_id=2)

    # else:
    #     print("bussines_ranking2が取得できませんでした")

    # paperbook_ranking
    if paperbook_ranking:
        saved_result = paperbook_ranking['Items']

        # paperbook_image = []
        for i in saved_result:
            item = i["Item"]
            image = item["mediumImageUrls"][0]
            thumbnail_image = image["imageUrl"]
            item_url = item["itemUrl"]

            BookAPI.objects.create(
                ImageUrl=thumbnail_image, item_Url=item_url, book_id=3)

            # paperbook_image.append(image)
            # context["paperbook_image"] = paperbook_image
    else:
        print("paperbook_rankingが取得できませんでした")

    # if paperbook_ranking2:
    #     saved_result = paperbook_ranking2['Items']

    #     # paperbook_image = []
    #     for i in saved_result:
    #         item = i["Item"]
    #         image = item["mediumImageUrls"][0]
    #         thumbnail_image = image["imageUrl"]
    #         item_url = item["itemUrl"]

    #         BookAPI.objects.create(
    #             ImageUrl=thumbnail_image, item_Url=item_url, book_id=3)

    # else:
    #     print("paperbook_ranking2が取得できませんでした")

    return redirect("/book")

# Query送信後の処理


def search_books(request):

    try:
        request.method == "POST"
        search_query = request.POST["search_query"]

        # APIの雛型
        api = "https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404?format=json&title={}&applicationId=1091122717356551414&hits=30".format(
            search_query)

        # 実際にAPIにリクエストを送信して結果を取得する
        search_books_api = requests.get(api).text
        # 結果はJSON形式なのでデコードする
        search_books = json.loads(search_books_api)
        # 結果を表示
        if search_books:
            saved_result = search_books['Items']
            book_data = []

            for i in saved_result:
                item = i["Item"]
                title = item["title"]
                itemUrl = item["itemUrl"]

templates/book/book_save.html
{% extends 'mysite/base.html' %}
{% load static %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">
{% endblock %}

{% block content %}
<main class="d-flex flex-row">
    
    <div class="page-wrapper d-flex flex-row h-100 w-100">
        
        {% include 'mysite/snippets/sidebar.html' %}

      <!-- 全ページの右のコンテンツ -->
        <div class="page-content h-100 w-100" >

            {% include 'mysite/snippets/header.html' %}
            {% include 'mysite/snippets/small_header.html' %}
            <!-- 下のコンテンツ -->
            <div class="big-display">  
                
                <form class="input-group w-25 float-right mx-4 my-4" action="{% url 'book:search_books' %}" method="POST">
                    {% csrf_token %}
                    <input type="search" name="search_query" class="form-control input-group-prepend" placeholder="書籍のタイトルを入力"></input>
                    <span class="input-group-btn input-group-append">
                    <button type="submit" name="btn-search" class="btn btn-primary"><i class="fas fa-search"></i> 検索</button>
                    </span>
                </form>

                <div class="save_header w-40">
                    <p class="save_result_title pt-3">書籍保存画面</p>
                </div>

                <!-- 書籍登録画面  -->
                <div class="saved_book_display w-100 pt-2">
                    <div class="saved_book_row d-flex flex-row pb-4">
                        <img src="{{largeImageUrl}}" class="saved_book_img">
                        <div class="right-row w-100 pl-4">
                            <p class="saved_book_title">{{title}}</p>
                            <div class="book_detail d-flex flex-colum">
                                <p class="pr-4">著者・作者:　<strong>{{author}}</strong></p>
                                <p>出版日:　<strong>{{salesDate}}</strong></p>
                            </div>
                            <div class="book_detail d-flex flex-colum w-100">
                                <p>出版社:　<strong>{{publisherName}}</strong></p>
                                <p class="pl-4">ジャンル:　<strong>{{genre}}</strong></p>
                            </div>
                            <div class="book_detail d-flex flex-colum w-100">
                                <p>定価:　<strong>{{itemPrice}}円</strong></p>
                                <p class="pl-4">評価:　<strong>{{reviewAverage}} / 5.0</strong></p>
                            </div>

                            <form class="" action="{% url 'book:saved_book' %}" method="POST">
                                {% csrf_token %}
                                <p class="movie_detail mt-1　mb-0">評価を選択してください</p>
                                <select name="vote_rate" size="1">
                                    <option value="評価なし">評価なし</option>
                                    {% with ''|center:10 as range %}
                                    {% for _ in range %}
                                        <option value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                                    {% endfor %}
                                    {% endwith %}
                                </select>
                                <p class="book_detail　pt-3 mb-0">感想・要約を入力してください</p>
                                <textarea type="search" name="sum_text" class="form-control input-group-prepend"></textarea>
                                <br>
                                <button type="submit" name="save_btn" class="btn btn-primary" value={{isbn}}>保存</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- 書籍登録画面  -->

            </div>
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}

templates/book/books.html
{% extends 'mysite/base.html' %}
{% load static %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">
{% endblock %}
 
{% block content %}
<main class="h-100">
    <div class="page-wrapper d-flex flex-row h-100 w-100">
      
      {% include 'mysite/snippets/sidebar.html' %}
      
      <!-- 全ページの右のコンテンツ -->
        <div class="page-content h-100 w-100" >

            {% include 'mysite/snippets/header.html' %}
            {% include 'mysite/snippets/small_header.html' %}
            
            <!-- 下のコンテンツ -->
            <div class="big-display h-100">
              <p class="movie_home_title mb-1 ml-5">Book Groupe</p>
              <form class="input-group w-25 float-right mx-4 mb-4 mt-5" action="{% url 'book:search_books' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="search_query" class="form-control input-group-prepend" placeholder="書籍のタイトルを入力"></input>
                <span class="input-group-btn input-group-append">
                  <button type="submit" name="btn-search" class="btn btn-primary"><i class="fas fa-search"></i> 検索</button>
                </span>
              </form>
             
              <div class="movie_content d-flex flex-row w-100">
                <!-- saved_movie -->
                <div class="saved_book ml-5 mr-4 d-flex flex-column">
                  <p class="saved_header pl-1 mb-1">ユーザーが最近読んだ書籍</p>
                  <!-- saves_movie_row -->
                  {% for book in db_books %}
                  <div class="saved_book-row d-flex flex-row mb-1">
                    <img src="{{book.ImageUrl}}" class="saved_img p-1">
                    <div class="d-flex flex-column pl-2 w-100">
                      <div class="top_saved_row pt-2 mb-1 d-flex flex-row"> 
                        <p class="saved_title mb-0">書籍名: <strong>{{book.title}}</strong></p>
                      </div>
                      <div class="d-flex flex-row">
                        <p class="release_date pr-3 m-0">公開日: {{book.salesDate}}</p>
                        <p class="vote_average pr-3 m-0">視聴日: {{book.created_at|date:"Y-m-j"}}</p>
                        <p class="vote_average m-0">評価: {{book.vote_rate}}</p>
                      </div>
                      <div class="under_row d-flex flex-row">
                        <p class="auther_name mb-0 mr-3">created by <strong>{{book.auther}}</strong></p>
                        {% if user.id == book.user_id %}
                        <form class="save_button pt-1 pr-2" action="{% url 'book:edit_book' %}" method="POST">
                          {% csrf_token %} 
                          <button type="submit" name="db_edit_btn" class="btn btn-sm btn-secondary" value={{book.id}}>編集</button>
                        </form>
                         
                        <form class="save_button pt-1" action="{% url 'book:saved_book' %}" method="POST">
                          {% csrf_token %} 
                          <button type="submit" name="db_delete_btn" class="btn btn-sm btn-danger" value={{book.id}}>削除</button>
                        </form>
                        {% endif %}
                      </div> 
                    </div>　
                  </div>
                  {% endfor %}
                  <!-- saves_movie_row -->
                </div>
                <!-- saved_movie -->

                <div　class="recommend_book d-flex flex-column w-100">
                  <!-- now_loading -->
                  <p class="now_mov_header pb-1 mb-0">最新小説本ランキング</p>
                  <div class="now_loading_book d-flex flex-row">
                    {% for essay in got_book1 %}
                    <!-- 467 × 146 -->
                      <img src="{{essay.ImageUrl}}" class="book_img py-1 px-1">
                    {% endfor %}
                  </div>
                
                  <!-- now_loading -->
                  <p class="now_mov_header mt-2 pb-1 mb-0">最新ビジネス本ランキング</p>
                  <div class="now_loading_book d-flex flex-row">
                    {% for bussines in got_book2 %}
                    <!-- 467 × 146 -->
                      <img src="{{bussines.ImageUrl}}" class="book_img py-1 pr-2">
                    {% endfor %}
                  </div>
               
                  <!-- now_loading -->
                  <p class="now_mov_header mt-2 pb-1 mb-0">最新技術本ランキング</p>
                  <div class="now_loading_book d-flex flex-row">
                    {% for paperbook in got_book3 %}
                    <!-- 467 × 146 -->
                      <img src="{{paperbook.ImageUrl}}" class="book_img py-1 px-1">
                    {% endfor %}
                  </div>
                  {% if user.id == 1 %}
                  <form class="reload_btn pt-2 pl-4" method="POST" action="{% url 'book:reload_data' %}">
                    {% csrf_token %}
                    <button type="submit" name="reload_btn" class="btn btn-primary">更新</button>
                  </form>
                  {% endif %}
                </div>

              </div>
            </div>
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}

templates/book/edit_book.html
{% extends 'mysite/base.html' %}
{% load static %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">
{% endblock %}

{% block content %}
<main class="d-flex flex-row">
    
    <div class="page-wrapper d-flex flex-row h-75 w-100">
        
        {% include 'mysite/snippets/sidebar.html' %}

      <!-- 全ページの右のコンテンツ -->
        <div class="page-content h-100 w-100" >

            {% include 'mysite/snippets/header.html' %}
            {% include 'mysite/snippets/small_header.html' %}
            <!-- 下のコンテンツ -->
            <div class="big-display">  
                
                <form class="input-group w-25 float-right mx-4 my-4" action="{% url 'book:search_books' %}" method="POST">
                    {% csrf_token %}
                    <input type="search" name="search_query" class="form-control input-group-prepend" placeholder="書籍のタイトルを入力"></input>
                    <span class="input-group-btn input-group-append">
                    <button type="submit" name="btn-search" class="btn btn-primary"><i class="fas fa-search"></i> 検索</button>
                    </span>
                </form>

                <div class="save_header w-40">
                    <p class="save_result_title pt-3">書籍編集画面</p>
                </div>

                <!-- 書籍登録画面  -->
                <div class="saved_movie_display w-100 pt-2">
                    {% for book in db_book %}
                    <div class="db_movie_row d-flex flex-row">
                        <img src="{{book.ImageUrl}}" class="db_book_img">
                        <div class="right-row w-100 pl-4">
                            <div class="movie_detail d-flex flex-colum">
                                <p class="saved_movie_title mb-0 pr-4">{{book.title}}</p>
                            </div>
                            <p class="db_release_date">出版日:　<strong>{{book.salesDate}}</strong></p>

                            <!-- 変更処理をviewでやれるようにIDを送る -->
                            <form action="{% url 'book:saved_book' %}" method="POST">
                                {% csrf_token %}
                                <p class="movie_detail mt-1　mb-0">ユーザー評価</p>
                                <select name="vote_rate" size="1">
                                    <option value="{{book.vote_rate}}">{{book.vote_rate}}</option>
                                    {% with ''|center:10 as range %}
                                    {% for _ in range %}
                                        <option value="{{ forloop.counter }}">{{ forloop.counter }}</option>
                                    {% endfor %}
                                    {% endwith %}
                                </select>
                                <p class="movie_detail　pt-4 mb-0">感想・要約を入力してください</p>
                                <textarea type="search" name="sum_text" class="form-control input-group-prepend">{{book.summary}}</textarea>
                                <input type="hidden" name="btn_from" value="{{btn_from}}">
                                <button type="submit" name="db_edit_btn" class="btn btn-primary mt-2 mr-2" value={{book.id}}>変更を保存</button>
                                <button type="submit" name="db_delete_btn" class="btn btn-danger mt-2" value={{book.id}}>データを削除</button>
                            </form>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- 書籍登録画面  -->

            </div>
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}

templates/book/user_books.html
{% extends 'mysite/base.html' %}
{% load static %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">
{% endblock %}

{% block content %}
<main class="h-100">
    <div class="page-wrapper d-flex flex-row h-100 w-100">
      
      {% include 'mysite/snippets/sidebar.html' %}
      
      <!-- 全ページの右のコンテンツ -->
        <div class="page-content h-100 w-100" >

            {% include 'mysite/snippets/header.html' %}
            {% include 'mysite/snippets/small_header.html' %}
            <!-- 下のコンテンツ -->
            <div class="big-display h-100">
              <form class="input-group w-25 float-right mx-4 mb-2 mt-5" action="{% url 'book:search_books' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="search_query" class="form-control input-group-prepend" placeholder="書籍のタイトルを入力"></input>
                <span class="input-group-btn input-group-append">
                  <button type="submit" name="btn-search" class="btn btn-primary"><i class="fas fa-search"></i> 検索</button>
                </span>
              </form>


              <div class="search_header">
                <p class="search_result_title">{{search_title}}</p>
              </div>

              <!-- search_movie_all -->
              <div class="search_result px-5">
                {% for book in book_data %}
                <!-- movie_row -->
                <div class="movie-row d-flex flex-row mx-3 mb-4" style="border: 1px solid rgb(0, 0, 0, 0.1);"> 
                  <img src="{{book.image}}" class="movie_img p-2">
                  <div class="p-2 w-100">
                    <div class="top_row>"> 
                      <div class="scroll_title d-flex w-100">
                        <p class="movie_title mb-1">{{book.title}}</p>
                      </div>
                      <div class="d-flex flex-row pt-2">
                        <p class="pr-4 mb-2">著者・作者:　<strong>{{book.author}}</strong></p>
                        <p class="mb-2">出版日:　<strong>{{book.salesDate}}</strong></p>                        
                      </div>
                      <div class="search_review d-flex flex-row">
                        <p class="mb-0 mb-1">出版社:　<strong>{{book.publisherName}}</strong></p>
                        <p class="pl-4 mb-1">評価:　<strong>{{book.reviewAverage}} / 5.0</strong></p>                  
                      </div>
                      <a href="{{book.itemUrl}}" class="detail_btn mt-0">詳細ページへ</a>
                    </div>                    
                    <!-- ここに線を入れたい -->
                    <div class="under_row d-flex flex-row">
                      <p class="m-0 mt-2">いいねボタン</p>
                      <p class="m-0 mt-2 px-3">タグ一覧</p>
                      {% if user.is_authenticated %}
                      <form class="save_button pt-1" action="{% url 'book:user_book' %}" method="POST">
                        {% csrf_token %} 
                        <button type="submit" name="save_btn" class="btn btn-primary" value={{book.isbn}}>保存画面に進む</button>
                      </form>
                      {% else %}
                      <form class="save_button pt-1" action="/login/" method="POST">
                        {% csrf_token %} 
                        <button type="submit" name="save_btn" class="btn btn-primary" value={{book.isbn}}>保存画面に進む</button>
                      </form>
                      {% endif %}
                    </div>
                  </div> 
                </div>
                {% endfor %}
                <!-- movie_row -->
              </div>
              <!-- search_movie_all -->

            </div>
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}