blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("test/", views.test)
]

book/urls.py
from django.urls import path, include
from . import views

app_name = "book"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_book, name="saved_book"),
    path("user_books/", views.search_books, name="search_books"),
    path("reload_ok", views.reload_data, name="reload_data"),
    path("save_book/", views.user_book, name="user_book"),
    path("edit_book/", views.edit_book, name="edit_book"),
    path("mypage_edit_book/", views.mypage_edit_book, name="mypage_edit_book"),
    path("mypage_delete_book/", views.mypage_delete_book,
         name="mypage_delete_book"),
]

comfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('contact/', views.contact),

    path('mypage/', include("mypage.urls")),
    path('movie/', include("movie.urls")),
    path('blog/', include("blog.urls")),
    path('idea/', include("idea.urls")),
    path('book/', include("book.urls")),
    path('english/', include("english.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.urls import path, include
from . import views

app_name = "idea"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.idea_home, name="idea_home"),
    path("save_idea/", views.save_idea, name="save_idea"),
    path('user_idea/<int:idea_id>/', views.user_idea, name='user_idea'),
    path("idea_edit/", views.idea_edit, name="idea_edit"),
]

movie/urls.py
from django.urls import path, include
from . import views

app_name = "movie"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_movie, name="saved_movie"),
    path("user_movies/", views.search_movies, name="search_movies"),
    path("save_movie/", views.user_movie, name="user_movie"),
    path("edit_movie/", views.edit_movie, name="edit_movie"),
    path("mypage_edit_movie/", views.mypage_edit_movie, name="mypage_edit_movie"),
    path("mypage_delete_movie/", views.mypage_delete_movie,
         name="mypage_delete_movie"),
    path("like=<int:id>/", views.like, name="like"),
]

mypage/urls.py
from django.urls import path, include
from . import views

app_name = "mypage"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.mypage, name="mypage"),
    path("my_edit/", views.profile_edit, name="profile_edit"),
    path("email_save/", views.profile_email_save, name="profile_email_save"),
    path("password_save/", views.profile_password_save,
         name="profile_password_save"),
    path("my_movie/", views.mypage_tab1, name="mypage_tab1"),
    path("my_book/", views.mypage_tab2, name="mypage_tab2"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/<int:idea_id>/", views.mypage_tab3_user, name="mypage_tab3_user"),
    path("my_english/", views.mypage_tab5, name="mypage_tab5"),
]

mypage/models.py
from django.db import models

# Create your models here.

mypage/forms.py
from django import forms
from django.core.exceptions import ValidationError
from mysite.models import User

# ログイン
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


class ChangePasswordForm(forms.Form):
    """パスワード変更"""
    current_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )
    new_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )
    confirm_new_password = forms.CharField(
        required=True,
        max_length=255,
        min_length=6,
        widget=forms.PasswordInput(),
    )

    def __init__(self, user_id, *args, **kwargs):
        self.user_id = user_id
        super().__init__(*args, **kwargs)

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']
        user = User.objects.get(id=self.user_id)
        if user.username and current_password:
            auth_result = authenticate(
                username=user.username,
                password=current_password,
            )
            if not auth_result:
                raise ValidationError('現在のパスワードが間違っています。')
        return current_password

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        return new_password

    def clean_confirm_new_password(self):
        confirm_new_password = self.cleaned_data['confirm_new_password']
        return confirm_new_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = self.cleaned_data.get('new_password')
        confirm_new_password = self.cleaned_data.get('confirm_new_password')
        if new_password != confirm_new_password:
            self.add_error(
                field='confirm_new_password',
                error=ValidationError('パスワードが一致しません。'))
        return cleaned_data


# 画像アップロード(modelの定義)
class UploadForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('account_image',)

mypage/views.py
from django.shortcuts import render, redirect
from movie.models import UserMovie
from book.models import UserBook
from idea.models import UserIdea, ThreadComment
from english.models import UserEnglish
from mysite.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from mypage.forms import UploadForm


def mypage(request):
    context = {}
    user_id = request.user.id
    db_movie_objs = UserMovie.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_book_objs = UserBook.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_idea_objs = UserIdea.objects.filter(
        user_id=user_id).order_by("id").reverse()[:1]
    db_english_objs = UserEnglish.objects.filter(
        user_id=user_id).order_by("id").reverse()[:4]

    # 総数取得
    movie_count = UserMovie.objects.all().filter(
        user_id=user_id).count()
    book_count = UserBook.objects.all().filter(
        user_id=user_id).count()
    idea_count = UserIdea.objects.all().filter(
        user_id=user_id).count()
    english_count = UserEnglish.objects.all().filter(
        user_id=user_id).count()

    db_user_objs = User.objects.all().filter(id=user_id)

    context["latest_movie"] = db_movie_objs
    context["latest_book"] = db_book_objs
    context["latest_idea"] = db_idea_objs
    context["latest_english"] = db_english_objs
    context["user_profile"] = db_user_objs

    context["movie_count"] = movie_count
    context["book_count"] = book_count
    context["idea_count"] = idea_count
    context["english_count"] = english_count

    return render(request, "mypage/mypage.html", context)


# プロフィール編集処理
def profile_edit(request):

    # プロフィール情報表示する
    try:
        context = {}
        if request.method == "POST":
            # 画像アップロード
            form = UploadForm(request.POST, request.FILES,)
            context["form"] = form

            profile_id = request.POST["profile_edit"]
            db_user_objs = User.objects.all().filter(id=profile_id)
            context["profile_data"] = db_user_objs

    except:
        print("プロフィールデータが取得出来ませでした")

    return render(request, "mypage/profile_edit.html", context)


def profile_email_save(request):

    # ユーザー情報(email)DB変更処理
    if request.method == "POST":
        profile_id = request.POST["email_edit"]
        account_image = request.POST.get("account_image")
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        user_name = request.POST["user_name"]
        user_email = request.POST["user_email"]
        print(account_image, "aaaaaaa")

        User.objects.filter(id=profile_id).update(
            firstName=first_name, lastName=last_name, username=user_name, email=user_email, account_image=account_image)

    else:
        print("ユーザー情報が取得出来ませでした")

    return redirect("/mypage")


def profile_password_save(request):

    # パスワード変更処理
    if request.method == "POST":
        profile_id = request.POST["password_edit"]

        # inputされたパスワード
        now_password = request.POST["now_password"]

        # DBのハッシュ化されているパスワード取得
        now_db = User.objects.get(id=profile_id)
        now_db_password = now_db.password

        if now_password:
            new_password = request.POST["new_password"]
            new_password_again = request.POST["new_password_again"]

            if new_password == new_password:
                User.objects.filter(id=profile_id).update(
                    password=new_password_again)

            else:
                print("新しいパスワードが同じではありません")
        else:
            print("パスワードが違います")

    else:
        print("パスワード情報が取得出来ませでした")

    return redirect("/mypage")


def mypage_tab1(request):

    user_id = request.user.id
    db_objs = UserMovie.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)
    page = request.GET.get('page', 1)
    obj_count = UserMovie.objects.all().count()
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    context = {'pages': pages, 'count': obj_count}

    return render(request, "mypage/mypage_segment/mypage_tab1.html", context)


def mypage_tab2(request):

    user_id = request.user.id
    db_objs = UserBook.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)

    page = request.GET.get('page', 1)
    obj_count = UserBook.objects.all().count()

    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    context = {'pages': pages, 'count': obj_count}

    return render(request, "mypage/mypage_segment/mypage_tab2.html", context)


def mypage_tab3(request):

    context = {}
    image_array = []

    user_id = request.user.id
    objs = UserIdea.objects.filter(user_id=user_id).order_by("id")[::-1]
    obj_count = UserIdea.objects.all().count()
    if objs:
        context["db_ideas"] = objs
        for obj in objs:
            # account_image取り出し
            user_id = obj.user_id
            objs = User.objects.filter(id=user_id)
            for obj in objs:
                account_image = obj.account_image
                image_array.append(account_image)

        context["account_image"] = image_array
        context["obj_count"] = obj_count
    else:
        print("DBから所得できてない")

    return render(request, "mypage/mypage_segment/mypage_tab3.html", context)


def mypage_tab3_user(request, idea_id):
    context = {}

    "通常表示用"
    context = {}
    image_array = []
    objs = UserIdea.objects.order_by("id")[::-1][:10]
    obj_count = UserIdea.objects.all().count()
    if objs:
        context["db_ideas"] = objs
        for obj in objs:
            # account_image取り出し
            user_id = obj.user_id
            objs = User.objects.filter(id=user_id)
            for obj in objs:
                account_image = obj.account_image
                image_array.append(account_image)

        context["account_images"] = image_array
        context["obj_count"] = obj_count
    else:
        print("DBから所得できてない")

    # コメント投稿後処理
    request.method == "POST"
    if request.POST.get("add_comment_btn"):
        idea_id = request.POST.get("add_comment_btn")
        if idea_id:
            comment_user_id = request.POST["user_id"]
            user_info = User.objects.get(id=comment_user_id)
            account_image = user_info.account_image
            comment_username = request.POST["user_name"]
            got_comment = request.POST["comment_form"]
            ThreadComment.objects.create(
                user_id=comment_user_id, username=comment_username, account_image=account_image, idea_id=idea_id, comment=got_comment)
    else:
        print("コメント投稿後処理ができませんでした")

    # コメント削除ボタン処理
    try:
        edit_id = request.POST["comment_delete_btn"]
        if edit_id:
            ThreadComment.objects.filter(id=edit_id).delete()
        else:
            print("edit_idが受け取れませんでした。")
    except:
        print("削除処理失敗しました")

    # 選択されたIdeaの詳細
    user_idea = UserIdea.objects.get(id=idea_id)
    if user_idea:
        context["idea_id"] = user_idea.id
        context["user_id"] = user_idea.user_id
        context["idea_title"] = user_idea.idea_title
        context["username"] = user_idea.username
        context["idea_detail"] = user_idea.idea_detail
        context["idea_from"] = user_idea.idea_from
        context["idea_tag"] = user_idea.idea_tag
        context["created_at"] = user_idea.created_at
        context["idea_price"] = user_idea.idea_price
        context["idea_target"] = user_idea.idea_target
        context["idea_for"] = user_idea.idea_for
        # tag取り出し
        idea_tag = user_idea.idea_tag
        idea_tag = idea_tag.replace(",", " ").replace(
            "、", " ").replace("　", " ").replace(".", "")
        tag_list = idea_tag.split(" ")
        context["idea_tag"] = tag_list

        # account画像取り出し
        got_id = user_idea.user_id
        objs = User.objects.get(id=got_id)
        context["account_image"] = objs.account_image

        # commentの取得
        # 全て表示
        comment_count = ThreadComment.objects.filter(idea_id=idea_id).count()
        more_btn = request.POST.get("more_btn")
        if more_btn:
            print(more_btn)
            user_comment = ThreadComment.objects.filter(idea_id=idea_id)
            context["comment_count"] = 1
        # 初期表示
        else:
            user_comment = ThreadComment.objects.filter(idea_id=idea_id)[:2]
            context["comment_count"] = comment_count
        context["user_comment"] = user_comment
        context["user_comment_id"] = idea_id

    else:
        print("DBから所得できてない")
    return render(request, 'mypage/mypage_segment/mypage_tab3_user.html', context)


def mypage_tab5(request):

    context = {}

    # 単語の表示
    user_id = request.user.id
    db_objs = UserEnglish.objects.filter(
        user_id=user_id).order_by("id").reverse()

    paginator = Paginator(db_objs, 18)

    page = request.GET.get('page', 1)
    obj_count = UserEnglish.objects.all().count()

    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)

    # checkボタンDB保存
    check_content = request.POST.getlist("check_content")
    saved_id = request.POST.get("check_save_btn")

    if check_content:
        if "1times" in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_1="checked")
        elif "1times" not in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_1="unchecked")

        if "2times" in check_content:
            UserEnglish.objects.filter(
                id=saved_id).update(checkbox_2="checked")

templates/mypage/mypage_home/latest_book.html
{% load static %}
{% for book in latest_book %}
<p　class="latest_row_title mb-1">最近読んだ書籍</p>
<div class="saved_book-row d-flex flex-row mb-1">
    <img src="{{book.ImageUrl}}" class="saved_img p-1">
    <div class="d-flex flex-column pl-2 w-100">
        <div class="top_saved_row pt-2 mb-1 d-flex flex-row"> 
        <p class="saved_title mb-0">書籍名: <strong>{{book.title}}</strong></p>
        </div>
        <div class="d-flex flex-row">
        <p class="release_date pr-3 m-0">公開日: {{book.salesDate}}</p>
        <p class="vote_average pr-3 m-0">視聴日: {{book.created_at|date:"Y-m-j"}}</p>
        <p class="vote_average m-0">評価: {{book.vote_rate}}</p>
        </div>
        <div class="under_row d-flex flex-row">
        <p class="auther_name mb-0 mr-3">created by <strong>{{book.auther}}</strong></p>
        {% if user.is_authenticated %}
        <form class="save_button pt-1 pr-2" action="{% url 'book:mypage_edit_book' %}" method="POST">
            {% csrf_token %} 
            <button type="submit" name="mypage_edit_btn" class="btn btn-sm btn-secondary" value={{book.id}}>編集</button>
        </form>
            
        <form class="save_button pt-1" action="{% url 'book:mypage_delete_book' %}" method="POST">
            {% csrf_token %} 
            <button type="submit" name="mypage_delete_btn" class="btn btn-sm btn-danger" value={{book.id}}>削除</button>
        </form>
        {% endif %}
        </div> 
    </div>　
</div>
{% endfor %}

templates/mypage/mypage_home/latest_english.html
{% load static %}
{% load boost %}
<div class="user_english mx-4 my-4">
    <div class="d-flex flex-row">
      <p class="now_mov_header pb-1 mb-0">マイ単語帳</p>
      <a href="{% url 'mypage:mypage_tab5' %}" class="more_english_btn">もっと見る</a>
    </div>
    {% for vocablary in latest_english%}
    <div class="user_english_row d-flex flex-column mb-2">
      <p class="user_search_text my-1 pl-1 pr-2">{{vocablary.query_lang}}: <strong>{{vocablary.search_text}}</strong></p>
      <p class="user_result my-1 pl-2 pr-2">{{vocablary.changed_lang}}: <strong>{{vocablary.changed_text}}</strong></p>
    </div>
    {% endfor %}
</div>

templates/mypage/mypage_home/latest_idea.html
{% load static %}
<p　class="latest_row_title mb-1">最近投稿したアイデア</p>
{% for idea in latest_idea %}
<div class="saved_idea_row d-flex flex-row mb-1">
    <div class="saved_idea d-flex flex-row px-3 pt-2 pb-1 w-100">
        <div class="right_idea_row d-flex flex-column w-100">
          <div class="user_idea_title_row h-50">
            <a href="{% url 'idea:user_idea' idea_id=idea.id %}" class="latest_idea_title mr-2 mb-0" id="title_clicked">{{idea.idea_title}}</a>
          </div>
          <div class="user_name_row d-flex flex-row h-50 mb-2">
            <p class="pr-3 mb-0">いいね</p>
            <p class="created_at pr-3 m-0">{{idea.created_at|date:"Y-m-d"}}</p>
            <p class="username mb-0">{{idea.username}}</p>
            {% if user.id == idea.user_id %}
              <form class="save_button ml-3 mt-0" action="{% url 'idea:idea_edit' %}" method="POST">
                {% csrf_token %} 
                <button type="submit" name="db_edit_btn" class="btn btn-sm btn-secondary" value={{idea.id}}>編集</button>
              </form>
            {% endif %}
          </div>
        </div>
      </div>
</div>
{% endfor %}

templates/mypage/mypage_home/latest_movie.html
{% load static %}
<p　class="latest_row_title mb-1">最近見た映画</p>
{% for movie in latest_movie %}
<div class="saved_movie-row d-flex flex-row mb-1">
    <img src="https://image.tmdb.org/t/p/w92{{movie.poster_path}}" class="saved_img p-1">
    <div class="d-flex flex-column pl-2 w-100">
        <div class="top_saved_row pt-2 mb-1 d-flex flex-row">
            <p class="saved_title mb-0">題名:<strong>{{movie.title}}</strong></p>
        </div>
        <div class="d-flex flex-row pb-1">
            <p class="release_date pr-3 m-0">公開日: {{movie.release_date}}</p>
            <!-- 視聴日 from DB -->
            <p class="vote_average pr-3 m-0">視聴日: {{movie.created_at|date:"Y-m-d"}}</p>
            <p class="saved_title mb-0">評価: {{movie.vote_rate}}</p>
        </div>
        
        <div class="under_row d-flex flex-row mt-1">
            <p class="auther_name mb-0 mr-3">created by <strong>{{movie.auther}}</strong></p>
            {% if user.is_authenticated %}
            <form class="save_button pt-1 pr-2" action="{% url 'movie:mypage_edit_movie' %}" method="POST">
                {% csrf_token %} 
                <button type="submit" name="mypage_edit_btn" class="btn btn-sm btn-secondary" value={{movie.id}}>編集</button>
            </form>
            
            <form class="save_button pt-1" action="{% url 'movie:mypage_delete_movie' %}" method="POST">
                {% csrf_token %} 
                <button type="submit" name="mypage_delete_btn" class="btn btn-sm btn-danger" value={{movie.id}}>削除</button>
            </form>
            {% endif %}
        </div> 
    </div>
</div>
{% endfor %}