blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("test/", views.test)
]

book/urls.py
from django.urls import path, include
from . import views

app_name = "book"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_book, name="saved_book"),
    path("user_books/", views.search_books, name="search_books"),
    path("reload_ok", views.reload_data, name="reload_data"),
    path("save_book/", views.user_book, name="user_book"),
    path("edit_book/", views.edit_book, name="edit_book"),
    path("mypage_edit_book/", views.mypage_edit_book, name="mypage_edit_book"),
    path("mypage_delete_book/", views.mypage_delete_book,
         name="mypage_delete_book"),
]

comfig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('contact/', views.contact),

    path('mypage/', include("mypage.urls")),
    path('movie/', include("movie.urls")),
    path('blog/', include("blog.urls")),
    path('idea/', include("idea.urls")),
    path('book/', include("book.urls")),
    path('english/', include("english.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.urls import path, include
from . import views

app_name = "idea"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.idea_home, name="idea_home"),
    path("save_idea/", views.save_idea, name="save_idea"),
    path('user_idea/<int:idea_id>/', views.user_idea, name='user_idea'),
    path("idea_edit/", views.idea_edit, name="idea_edit"),
]

movie/urls.py
from django.urls import path, include
from . import views

app_name = "movie"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.saved_movie, name="saved_movie"),
    path("user_movies/", views.search_movies, name="search_movies"),
    path("save_movie/", views.user_movie, name="user_movie"),
    path("edit_movie/", views.edit_movie, name="edit_movie"),
    path("mypage_edit_movie/", views.mypage_edit_movie, name="mypage_edit_movie"),
    path("mypage_delete_movie/", views.mypage_delete_movie,
         name="mypage_delete_movie"),
    path("like=<int:id>/", views.like, name="like"),
]

mypage/urls.py
from django.urls import path, include
from . import views

app_name = "mypage"
urlpatterns = [
    # Homeに戻るようにnameで固定化
    path("", views.mypage, name="mypage"),
    path("my_edit/", views.profile_edit, name="profile_edit"),
    path("email_save/", views.profile_email_save, name="profile_email_save"),
    path("password_save/", views.profile_password_save,
         name="profile_password_save"),
    path("my_movie/", views.mypage_tab1, name="mypage_tab1"),
    path("my_book/", views.mypage_tab2, name="mypage_tab2"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/", views.mypage_tab3, name="mypage_tab3"),
    path("my_idea/<int:idea_id>/", views.mypage_tab3_user, name="mypage_tab3_user"),
    path("my_english/", views.mypage_tab5, name="mypage_tab5"),
]

mysite/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )

    firstName = models.CharField(max_length=20, default="名字")
    lastName = models.CharField(max_length=20, default="名前")
    username = models.CharField(max_length=20, default="名無しユーザー")
    # 保存先検討
    account_image = models.ImageField(
        default="https://cdn2.aprico-media.com/production/imgs/images/000/029/940/original.png?1553946576", upload_to='images/', null=True)

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def __str__(self):
        return str(self.id)

mysite/forms.py
from .models import User
from django import forms
from django.contrib.auth import get_user_model


class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)
        # fields = '__all__'

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


# 必要か不明なため調べてから付属する
# from django.contrib.auth.forms import ReadOnlyPasswordHashField
# from .models import User
# class UserChangeForm(forms.ModelForm):
#     password = ReadOnlyPasswordHashField()

#     class Meta:
#         model = User
#         fields = ('email', 'password', 'date_of_birth',
#                   'is_active', 'is_admin')

#     def clean_password(self):
#         return self.initial["password"]

mysite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from mysite.forms import UserCreationForm
from django.core.mail import send_mail
import os


def index(request):
    context = {
        "title": "hello"
    }
    return render(request, "mysite/index.html", context)


# Login画面の表示(Djangoのデフォルト)
class Login(LoginView):
    template_name = "mysite/auth.html"


# サインアップしたデータをAdminに保存している
def signup(request):
    context = {}
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
    return render(request, "mysite/auth.html", context)


def contact(request):
    context = {}

    # email
    subject = "題名"
    message = "本文テスト"
    email_from = os.environ["DEFAULT_EMAIL_FROM"]
    email_to = [os.environ["DEFAULT_EMAIL_FROM"], ]
    send_mail(subject, message, email_from, email_to)

    return render(request, "mysite/snippets/contact.html", )

templates/mysite/snippets/contact.html
{% extends 'mysite/base.html' %}
{% load static %}
 
{% block head %} 
<!-- movieの子を適応されて欲しい。 --> 
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/small_header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/snippets/mypage.css' %}">
{% endblock %}

{% block content %}
<main class="h-100">
    <div class="page-wrapper d-flex flex-row h-100 w-100">
      
      {% include 'mysite/snippets/sidebar.html' %}
      
      <!-- 全ページの右のコンテンツ -->
      <div class="page-content h-100 w-100" >
          
          {% include 'mysite/snippets/header.html' %}
          {% include 'mysite/snippets/small_header.html' %}
            <div class="contact_content d-flex flex-column">
                <p class="contact_title pt-5">お問い合わせ</p>
                <div class="contact">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="d-flex flex-column px-4 pb-2 pt-3">
                            <label><strong>名前</strong></label>
                            <input type="text" id="id_name" name="name" placeholder="山田太郎"> 
                        </div>
    
                        <div class="d-flex flex-column px-4 py-2">
                            <label><strong>メールアドレス</strong></label>
                            <input type="email" id="id_email" name="email" placeholder="vantan@gmail.com"> 
                        </div>
    
                        <div class="d-flex flex-column px-4 py-2">
                            <label><strong>お問い合わせ内容</strong></label>
                            <textarea class="contact_textarea" name="content" rows="4"></textarea>
                        </div>
    
                        <div class="px-4 pt-2 pb-3">
                            <button type="submit" class="btn btn-primary">送信</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- 下のコンテンツ -->
            <!-- 下のコンテンツ -->
        </div>
      <!-- 全ページの右のコンテンツ -->
    </div>
</main>

{% endblock %}

templates/mysite/snippets/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<!-- レクチャー時点のalpha版を使用しています。betaや安定版を使用する場合はcssクラスが変更になっている可能性がありますので、適時修正してください -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<title>MySite</title>

templates/mysite/snippets/header.html
{% load static %}
<!-- トップバー -->
<nav class="navbar px-3 py-0 my-4 bg-light position-static justify-content-center" id="navbar">
    <div class="navbar-brand toggle_menu position-absolute start-0" id="toggle_menu">
        <button class="btn btn-light btn-sm" id="sidebarToggler">
            <i class="fas fa-bars fa-lg" id="sidebarTogglerFa"></i>
        </button>
    </div>
    <!-- 中央画像 -->
    <!-- text-muted mx-auto -->
    <a class="nav-item-image" href="/">
        <img src="{{ STATIC_URL }}img/header.jpg" class="text-muted" width="200" height="100" alt="サンプル">
    </a>
    <ul class="navbar-nav d-flex flex-row position-absolute end-0">
        <li class="nav-item-underline ml-3 text-muted">
            <a class="p-2 link-secondary" href="#" style="text-decoration:none;">ABOUT</a>
        </li>
        <li class="nav-item-underline ml-3 text-muted">
            <a class="p-2 link-secondary" href="/contact" style="text-decoration:none;">CONTACT</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item-underline mx-3 text-muted">
            <a class="p-2 link-secondary" href="{% url 'mypage:mypage' %}" style="text-decoration:none;">MYPAGE</a>
        </li>
        {% else %}
        <li class="nav-item-underline mx-3 text-muted">
            <a class="p-2 link-secondary" href="/login" style="text-decoration:none;">LOGIN</a>
            <a>/</a>
            <a class="p-2 link-secondary" href="/signup" style="text-decoration:none;">SIGNUP</a>
        </li>
        {% endif %}
    </ul>
</nav>
<!-- トップバー -->

templates/mysite/snippets/sidebar.html
<!-- サイトバーメニュー -->
<nav class="sidebar">
    <div class="pb-1 pt-5">
        <h4>
            MENU ALL
        </h4>
    </div>
    <ul class="nav flex-column m-o p-2">
        <li class="nav-item-menu mb-2">
            <a href="{% url 'movie:saved_movie' %}" class="nav-link">MOVIE</a> 
        </li>
        <li class="nav-item-menu mb-2">
            <a href="" class="nav-link">BLOG</a>
        </li>
        <li class="nav-item-menu mb-2">
            <a href="{% url 'idea:idea_home' %}" class="nav-link">IDEA</a>
        </li>
        <li class="nav-item-menu mb-2">
            <a href="{% url 'book:saved_book' %}" class="nav-link">Book</a>
        </li>
        <li class="nav-item-menu mb-2">
            <a href="{% url 'english:get_youtube_data' %}" class="nav-link">English</a>
        </li>
        <div class="pb-1 pt-5">
            <h4>
                LOGOUT
            </h4>
        </div>
        <li class="nav-item-menu mb-2">
            <a href="/logout" class="nav-link">Logout</a>
        </li>
    </ul>
</nav>
<!-- サイトバーメニュー -->

templates/mysite/snippets/small_header.html
<!-- 各appのHomeを作成してurlを通したらその都度urlを変更する -->
<!-- 小さいheader -->
<div class="main-wrapper" id="mainwrapper">
    <form class="img_container main-box1" action="{% url 'movie:saved_movie' %}" method="POST">
        <a class="box box1" href="{% url 'movie:saved_movie' %}">Movie</a>
    </form> 
    <div class="img_container main-box2">
        <a class="box box2" href="#">Blog</a>
    </div>
    <div class="img_container main-box3">
        <a class="box box3" href="{% url 'idea:idea_home' %}">Idea</a>
    </div>
    <form class="img_container main-box4" action="{% url 'book:saved_book' %}" method="POST">
        <a class="box box4" href="{% url 'book:saved_book' %}">Book</a>
    </form>
    <div class="img_container main-box5">
        <a class="box box5" href="{% url 'english:get_youtube_data' %}">English</a>
    </div>
</div>
<!-- 小さいheader --> 